#
# Filter setting for intranet environment.
# This setting is used by default.
# For details, check http://docs.asakusa-satellite.org/
#

info:
 version: 2

filters:
 - name: code_highlight_filter
# - name: quote_it
 - name: auto_link
 - name: revision_it_filter
 - name: redmine_ticket_link_filter
 - name: twitter_link
 - name: emoji_filter
# - name: emoticon_filter

plugins:
 - dir: as_desktopnotification
# - dir: as_global_js_css
# - dir: as_watage_plugin
 - dir: as_twitterauth_plugin
# - dir: as_localauth_plugin
# - dir: as_redmineauth_plugin
