#
# Filter setting for internet environment.
# To use this setting, set FILTER_NAME variable to 'filter.yml'.
# For details, check http://docs.asakusa-satellite.org/
#

info:
 version: 2

filters:
 - name: code_highlight_filter
 - name: quote_it
 - name: revision_it_filter
 - name: redmine_ticket_link_filter
 - name: twitter_link
 - name: emoji_filter

plugins:
 - dir: as_desktopnotification
 - dir: as_android_notifier
 - dir: as_iphone_notifier
 - dir: as_chrome_notifier
 - dir: as_profile_setting
 - dir: as_device_setting
 - dir: as_global_js_css
 - dir: as_watage_plugin
 - dir: as_localauth_plugin
